openapi: 3.0.1
info:
  title: GlobalBank Account API
  description: API to securely retrieve customer account details, balances, and transaction history.
  termsOfService: https://www.globalbank.com/terms
  contact:
    name: GlobalBank Support
    url: https://www.globalbank.com/support
  version: 1.0.0
  x-ibm-name: globalbank-account-api
externalDocs:
  description: GlobalBank API Documentation
  url: https://www.globalbank.com/api-docs
servers:
- url: /banking/v1
security:
- OAuth2: []
paths:
  /accounts:
    get:
      summary: Retrieve all accounts associated with the authenticated user.
      security:
      - OAuth2: []
      responses:
        "200":
          description: List of accounts successfully retrieved
          content:
            application/json:
              schema:
                title: Accounts List
                type: array
                items:
                  type: object
                  properties:
                    account_number:
                      type: string
                      example: "123456789"
                    account_type:
                      type: string
                      enum:
                        - CHECKING
                        - SAVINGS
                        - CREDIT_CARD
                      example: "CHECKING"
                    currency:
                      type: string
                      example: "USD"
  /accounts/{account_number}/transactions:
    get:
      summary: Retrieve transaction history for a specific account.
      security:
      - OAuth2: []
      parameters:
      - name: account_number
        in: path
        required: true
        description: The account number to fetch transactions for.
        schema:
          type: string
          example: "123456789"
      - name: start_date
        in: query
        required: true
        description: Start date for transaction history in YYYY-MM-DD format.
        schema:
          type: string
          format: date
          example: "2023-01-01"
      - name: end_date
        in: query
        required: true
        description: End date for transaction history in YYYY-MM-DD format.
        schema:
          type: string
          format: date
          example: "2023-01-31"
      responses:
        "200":
          description: Transaction history successfully retrieved
          content:
            application/json:
              schema:
                title: Transaction History
                type: array
                items:
                  type: object
                  properties:
                    transaction_id:
                      type: string
                      example: "TRX123456"
                    date:
                      type: string
                      format: date-time
                      example: "2023-01-15T10:30:00Z"
                    description:
                      type: string
                      example: "Payment to XYZ Retail"
                    amount:
                      type: number
                      format: float
                      example: -100.00
                    balance_after:
                      type: number
                      format: float
                      example: 1500.00
                    currency:
                      type: string
                      example: "USD"
  /accounts/{account_number}/balance:
    get:
      summary: Retrieve the current balance of a specific account.
      security:
      - OAuth2: []
      parameters:
      - name: account_number
        in: path
        required: true
        description: The account number to fetch the balance for.
        schema:
          type: string
          example: "123456789"
      responses:
        "200":
          description: Account balance successfully retrieved
          content:
            application/json:
              schema:
                title: Account Balance
                type: object
                properties:
                  account_number:
                    type: string
                    example: "123456789"
                  balance:
                    type: number
                    format: float
                    example: 1200.50
                  currency:
                    type: string
                    example: "USD"

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.globalbank.com/oauth2/authorize
          tokenUrl: https://auth.globalbank.com/oauth2/token
          scopes:
            read: Access to view account details, balances, and transactions
      x-ibm-oauth-provider: https://auth.globalbank.com/oauth2

x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  enforced: true
  assembly:
    execute:
    - invoke:
        title: account lookup
        target-url: $(target-url)
        timeout: 60
        version: 2.2.0  # Updated version to a supported version
    - invoke:
        title: transaction lookup
        target-url: $(target-url)/transactions
        timeout: 60
        version: 2.2.0  # Updated version to a supported version
    - invoke:
        title: balance lookup
        target-url: $(target-url)/balance
        timeout: 60
        version: 2.2.0  # Updated version to a supported version
  testable: true
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
