openapi: 3.0.1
info:
  title: Account Management and Transaction History
  description: Provides secure access to account balances and transaction history for customers.
  termsOfService: https://globalbank.com/terms
  contact:
    name: GlobalBank Support
    url: https://globalbank.com/contact
  version: 1.0.0
  x-bank-name: globalbank-api
externalDocs:
  description: API Documentation
  url: https://globalbank.com/docs/api
servers:
- url: /banking
security:
- OAuth2: []
paths:
  /accounts:
    get:
      summary: Retrieve list of all accounts for a customer
      security:
      - OAuth2: [read]
      responses:
        "200":
          description: Successful retrieval of accounts
          content:
            application/json:
              schema:
                title: Accounts
                type: array
                items:
                  type: object
                  properties:
                    account_number:
                      type: string
                      example: 1234567890
                    account_type:
                      type: string
                      enum:
                      - Checking
                      - Savings
                      - Credit Card
                      example: Checking
                    balance:
                      type: number
                      format: float
                      example: 1500.50
                    currency:
                      type: string
                      example: USD
        "401":
          description: Unauthorized - Invalid or expired OAuth2 token
  /accounts/{account_number}/transactions:
    get:
      summary: Retrieve transaction history for a specific account within a date range
      parameters:
      - name: account_number
        in: path
        description: The unique identifier for the account
        required: true
        schema:
          type: string
      - name: start_date
        in: query
        description: The start date for the transaction history in YYYY-MM-DD format
        required: true
        schema:
          type: string
          format: date
      - name: end_date
        in: query
        description: The end date for the transaction history in YYYY-MM-DD format
        required: true
        schema:
          type: string
          format: date
      responses:
        "200":
          description: Transaction history retrieved successfully
          content:
            application/json:
              schema:
                title: Transaction History
                type: array
                items:
                  type: object
                  properties:
                    transaction_id:
                      type: string
                      example: TX123456789
                    date:
                      type: string
                      format: date-time
                      example: 2024-09-01T10:30:00Z
                    amount:
                      type: number
                      format: float
                      example: -120.00
                    currency:
                      type: string
                      example: USD
                    description:
                      type: string
                      example: Grocery Store Purchase
                    category:
                      type: string
                      example: Food & Drink
        "400":
          description: Bad Request - Invalid date format or missing required parameters
        "401":
          description: Unauthorized - Invalid or expired OAuth2 token
        "404":
          description: Account not found
  /accounts/{account_number}/balance:
    get:
      summary: Retrieve current account balance
      parameters:
      - name: account_number
        in: path
        description: The unique identifier for the account
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Account balance retrieved successfully
          content:
            application/json:
              schema:
                title: Account Balance
                type: object
                properties:
                  account_number:
                    type: string
                    example: 1234567890
                  balance:
                    type: number
                    format: float
                    example: 3200.75
                  currency:
                    type: string
                    example: USD
        "401":
          description: Unauthorized - Invalid or expired OAuth2 token
        "404":
          description: Account not found
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.globalbank.com/oauth2/authorize
          tokenUrl: https://auth.globalbank.com/oauth2/token
          scopes:
            read: Grants read access to account data
            write: Grants write access to account data
x-ibm-configuration:
  properties:
    target-url:
      value: "https://api.globalbank.com/accounts"
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
