openapi: 3.0.1
info:
  title: GlobalBank Account API
  description: Securely view account balances and transaction history for GlobalBank customers.
  termsOfService: https://www.globalbank.com/terms
  contact:
    name: GlobalBank Support
    url: https://www.globalbank.com/support
  version: 1.0.0
  x-ibm-name: globalbank-account-api
externalDocs:
  description: "GitHub project for this API, containing source code and deployment pipeline"
  url: https://github.com/globalbank/api-docs
servers:
- url: /banking/v1
security:
- clientID: []
paths:
  /accounts:
    get:
      summary: Retrieve the list of accounts associated with the authenticated user.
      parameters: []
      responses:
        "200":
          description: Accounts successfully retrieved
          content:
            application/json:
              schema:
                title: Account List
                type: array
                items:
                  type: object
                  properties:
                    account_number:
                      title: Account Number
                      type: string
                      example: "1234567890"
                    account_type:
                      title: Account Type
                      type: string
                      enum:
                        - CHECKING
                        - SAVINGS
                        - CREDIT_CARD
                      example: "CHECKING"
                    currency:
                      title: Currency
                      type: string
                      example: "USD"
  /accounts/{account_number}/transactions:
    get:
      summary: Retrieve transaction history for a specific account within a date range.
      parameters:
      - name: account_number
        in: path
        description: The account number for which to retrieve transactions.
        required: true
        schema:
          type: string
          example: "1234567890"
      - name: start_date
        in: query
        description: Start date for the transaction history in YYYY-MM-DD format.
        required: true
        schema:
          type: string
          format: date
          example: "2023-01-01"
      - name: end_date
        in: query
        description: End date for the transaction history in YYYY-MM-DD format.
        required: true
        schema:
          type: string
          format: date
          example: "2023-01-31"
      responses:
        "200":
          description: Transactions successfully retrieved
          content:
            application/json:
              schema:
                title: Transaction History
                type: array
                items:
                  type: object
                  properties:
                    transaction_id:
                      title: Transaction ID
                      type: string
                      example: "TRX123456"
                    date:
                      title: Transaction Date
                      type: string
                      format: date-time
                      example: "2023-01-15T10:30:00Z"
                    description:
                      title: Transaction Description
                      type: string
                      example: "Payment to XYZ Retail"
                    amount:
                      title: Transaction Amount
                      type: number
                      format: float
                      example: -100.00
                    balance_after:
                      title: Balance After Transaction
                      type: number
                      format: float
                      example: 1500.00
                    currency:
                      title: Currency
                      type: string
                      example: "USD"
  /accounts/{account_number}/balance:
    get:
      summary: Retrieve the current balance of a specific account.
      parameters:
      - name: account_number
        in: path
        description: The account number for which to retrieve the balance.
        required: true
        schema:
          type: string
          example: "1234567890"
      responses:
        "200":
          description: Account balance successfully retrieved
          content:
            application/json:
              schema:
                title: Account Balance
                type: object
                properties:
                  account_number:
                    title: Account Number
                    type: string
                    example: "1234567890"
                  balance:
                    title: Current Balance
                    type: number
                    format: float
                    example: 1200.50
                  currency:
                    title: Currency
                    type: string
                    example: "USD"
components:
  securitySchemes:
    clientID:
      type: apiKey
      name: X-IBM-Client-Id
      in: header
x-ibm-configuration:
  properties:
    target-url:
      value: "https://main--lighthearted-torrone-3976db.netlify.app/.netlify/functions/fetch-data"
      description: URL to retrieve account and transaction data from Netlify
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  compatibility:
    suppress-limitation-errors: true
  assembly:
    execute:
    - invoke:
        title: account balance lookup
        version: 2.0.0
        target-url: $(target-url)/accounts/{account_number}/balance
        follow-redirects: false
        timeout: 60
        persistent-connection: true
        backend-type: json
        output: balance
    - parse:
        title: parse balance response
        version: 2.1.0
        input: balance
        output: balance
        description: Parse the JSON balance data to ensure it is in the correct format.
    - map:
        title: map balance response
        version: 2.0.0
        inputs:
          input:
            schema:
              type: object
              properties:
                balance:
                  type: number
                currency:
                  type: string
            variable: balance.body
        outputs:
          output:
            schema:
              type: object
              properties:
                account_number:
                  type: string
                balance:
                  type: number
                currency:
                  type: string
            variable: message.body
    - invoke:
        title: transaction lookup
        version: 2.0.0
        target-url: $(target-url)/accounts/{account_number}/transactions
        follow-redirects: false
        timeout: 60
        persistent-connection: true
        backend-type: json
        output: transactions
    - parse:
        title: parse transactions response
        version: 2.1.0
        input: transactions
        output: transactions
        description: Parse the JSON transaction data to ensure it is in the correct format.
    - map:
        title: map transactions response
        version: 2.0.0
        inputs:
          input:
            schema:
              type: object
              properties:
                transactions:
                  type: array
            variable: transactions.body
        outputs:
          output:
            schema:
              type: object
              properties:
                transactions:
                  type: array
            variable: message.body
    finally: []
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
