openapi: 3.0.1
info:
  title: GlobalBank Account API
  description: Securely view account balances and transaction history for GlobalBank customers.
  termsOfService: https://github.com/globalbank/api-terms
  contact:
    name: GlobalBank Corporation
    url: https://www.globalbank.com/products/api-connect
  version: 1.0.0
  x-ibm-name: globalbank-account-api
externalDocs:
  description: "Github project for this API, containing source code and deployment pipeline"
  url: https://github.com/globalbank/api-docs
servers:
- url: /banking/v1
security:
- clientID: []
paths:
  /accounts:
    get:
      summary: Retrieve the list of accounts associated with the authenticated user.
      parameters: []
      responses:
        "200":
          description: Accounts successfully retrieved
          content:
            application/json:
              schema:
                title: Account List
                type: array
                items:
                  type: object
                  properties:
                    account_number:
                      title: Account Number
                      type: string
                      example: "1234567890"
                    account_type:
                      title: Account Type
                      type: string
                      enum:
                        - CHECKING
                        - SAVINGS
                        - CREDIT_CARD
                      example: "CHECKING"
                    currency:
                      title: Currency
                      type: string
                      example: "USD"

  /accounts/{account_number}/transactions:
    get:
      summary: Retrieve the transaction history for a specific account within a date range.
      parameters:
      - name: account_number
        in: path
        description: The account number for which to retrieve transactions.
        required: true
        schema:
          type: string
          example: "1234567890"
      - name: start_date
        in: query
        description: The start date of the transaction history to retrieve (YYYY-MM-DD).
        required: true
        schema:
          type: string
          format: date
          example: "2023-01-01"
      - name: end_date
        in: query
        description: The end date of the transaction history to retrieve (YYYY-MM-DD).
        required: true
        schema:
          type: string
          format: date
          example: "2023-01-31"
      responses:
        "200":
          description: Transactions successfully retrieved
          content:
            application/json:
              schema:
                title: Transaction History
                type: array
                items:
                  type: object
                  properties:
                    transaction_id:
                      title: Transaction ID
                      type: string
                      example: "TRX123456"
                    date:
                      title: Transaction Date
                      type: string
                      format: date-time
                      example: "2023-01-15T10:30:00Z"
                    description:
                      title: Transaction Description
                      type: string
                      example: "Payment to ABC Retail"
                    amount:
                      title: Transaction Amount
                      type: number
                      format: float
                      example: -100.00
                    balance_after:
                      title: Balance After Transaction
                      type: number
                      format: float
                      example: 1500.00
                    currency:
                      title: Currency
                      type: string
                      example: "USD"

  /accounts/{account_number}/balance:
    get:
      summary: Retrieve the current balance of a specific account.
      parameters:
      - name: account_number
        in: path
        description: The account number for which to retrieve the balance.
        required: true
        schema:
          type: string
          example: "1234567890"
      responses:
        "200":
          description: Account balance successfully retrieved
          content:
            application/json:
              schema:
                title: Account Balance
                type: object
                properties:
                  account_number:
                    title: Account Number
                    type: string
                    example: "1234567890"
                  balance:
                    title: Current Balance
                    type: number
                    format: float
                    example: 1200.50
                  currency:
                    title: Currency
                    type: string
                    example: "USD"

components:
  securitySchemes:
    clientID:
      type: apiKey
      name: X-IBM-Client-Id
      in: header

x-ibm-configuration:
  properties:
    target-url:
      value: "https://api.globalbank.com/accounts"
      description: URL of the 
