openapi: 3.0.1
info:
  title: transactions-GlobalBank Account API
  description: Securely view account transactions for GlobalBank customers.
  termsOfService: https://www.globalbank.com/terms
  contact:
    name: GlobalBank Support
    url: https://www.globalbank.com/support
  version: 1.0.0
  x-ibm-name: transactions-globalbank-account-api
externalDocs:
  description: "GitHub project for this API, containing source code and deployment pipeline"
  url: https://github.com/globalbank/api-docs
servers:
  - url: /banking/v1
security:
  - clientID: []
paths:
  /accounts/{account_number}/transactions:
    get:
      summary: Retrieve the current transactions of a specific account.
      parameters:
        - name: account_number
          in: path
          description: The account number for which to retrieve the transactions.
          required: true
          schema:
            type: string
            example: "1234567890"
      responses:
        "200":
          description: Account transactions successfully retrieved
          content:
            application/json:
              schema:
                title: Account Transactions
                type: object
                properties:
                  account_number:
                    title: Account Number
                    type: string
                    example: "1234567890"
                  transactions:
                    title: List of Transactions
                    type: array
                    items:
                      type: object
                      properties:
                        transaction_id:
                          title: Transaction ID
                          type: string
                          example: "TRX123456"
                        date:
                          title: Transaction Date
                          type: string
                          format: date-time
                          example: "2023-01-15T10:30:00Z"
                        description:
                          title: Description
                          type: string
                          example: "Payment to ABC Retail"
                        amount:
                          title: Amount
                          type: number
                          format: float
                          example: -100.00
                        balance_after:
                          title: Balance After Transaction
                          type: number
                          format: float
                          example: 1100.50
                        currency:
                          title: Currency
                          type: string
                          example: "USD"
components:
  securitySchemes:
    clientID:
      type: apiKey
      name: X-IBM-Client-Id
      in: header
x-ibm-configuration:
  properties:
    target-url:
      value: "http://41.45.24.239/"
      description: URL to retrieve account transaction data from Netlify
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        title: account transactions lookup
        version: 2.0.0
        target-url: $(target-url)/accounts/{account_number}/transactions
        follow-redirects: false
        timeout: 60
        persistent-connection: true
        backend-type: json
        output: transactions
        description: Retrieves the list of transactions associated with the user.
    finally: []
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
x-original-swagger-version: "2.0"
