openapi: 3.0.1
info:
  title: GlobalBank Account API
  description: Securely view account balances and transaction history for GlobalBank customers.
  termsOfService: https://www.globalbank.com/terms
  contact:
    name: GlobalBank Support
    url: https://www.globalbank.com/support
  version: 1.0.0
  x-ibm-name: globalbank-account-api
externalDocs:
  description: "GitHub project for this API, containing source code and deployment pipeline"
  url: https://github.com/globalbank/api-docs
servers:
- url: /banking/v1
security:
- clientID: []
paths:
  /accounts:
    get:
      summary: Retrieve the list of accounts associated with the authenticated user.
      responses:
        "200":
          description: Accounts successfully retrieved
          content:
            application/json:
              schema:
                title: Account List
                type: array
                items:
                  type: object
                  properties:
                    account_number:
                      title: Account Number
                      type: string
                      example: "1234567890"
                    account_type:
                      title: Account Type
                      type: string
                      enum:
                        - CHECKING
                        - SAVINGS
                        - CREDIT_CARD
                      example: "CHECKING"
                    currency:
                      title: Currency
                      type: string
                      example: "USD"
  /accounts/{account_number}/transactions:
    get:
      summary: Retrieve transaction history for a specific account within a date range.
      parameters:
      - name: account_number
        in: path
        description: The account number for which to retrieve transactions.
        required: true
        schema:
          type: string
          example: "1234567890"
      responses:
        "200":
          description: Transactions successfully retrieved
          content:
            application/json:
              schema:
                title: Transaction History
                type: array
                items:
                  type: object
                  properties:
                    transaction_id:
                      title: Transaction ID
                      type: string
                      example: "TRX123456"
                    date:
                      title: Transaction Date
                      type: string
                      format: date-time
                      example: "2023-01-15T10:30:00Z"
                    description:
                      title: Transaction Description
                      type: string
                      example: "Payment to XYZ Retail"
                    amount:
                      title: Transaction Amount
                      type: number
                      format: float
                      example: -100.00
                    balance_after:
                      title: Balance After Transaction
                      type: number
                      format: float
                      example: 1500.00
                    currency:
                      title: Currency
                      type: string
                      example: "USD"
  /accounts/{account_number}/balance:
    get:
      summary: Retrieve the current balance of a specific account.
      parameters:
      - name: account_number
        in: path
        description: The account number for which to retrieve the balance.
        required: true
        schema:
          type: string
          example: "1234567890"
      responses:
        "200":
          description: Account balance successfully retrieved
          content:
            application/json:
              schema:
                title: Account Balance
                type: object
                properties:
                  account_number:
                    title: Account Number
                    type: string
                    example: "1234567890"
                  balance:
                    title: Current Balance
                    type: number
                    format: float
                    example: 1200.50
                  currency:
                    title: Currency
                    type: string
                    example: "USD"
components:
  securitySchemes:
    clientID:
      type: apiKey
      name: X-IBM-Client-Id
      in: header
x-ibm-configuration:
  properties:
    target-url:
      value: "https://main--lighthearted-torrone-3976db.netlify.app/.netlify/functions/fetch-data"
      description: URL to retrieve account and transaction data from Netlify
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        title: account list lookup
        version: 2.0.0
        target-url: $(target-url)/accounts
        follow-redirects: false
        timeout: 60
        persistent-connection: true
        backend-type: json
        output: accounts
        description: Retrieves the list of accounts associated with the user.
    - parse:
        version: 2.1.0
        title: parse account list
        parse-settings-reference:
          default: apic-default-parsesettings
        input: accounts
        output: accounts
        description: Parse the JSON from the account service so that the values can be used later in the flow.
    - map:
        version: 2.0.0
        title: map input to accounts
        inputs:
          input:
            schema:
              type: array
              items:
                type: object
                properties:
                  account_number:
                    type: string
                    name: account_number
                  account_type:
                    type: string
                    name: account_type
                  currency:
                    type: string
                    name: currency
            variable: accounts.body
        outputs:
          output:
            schema:
              type: array
              items:
                type: object
                properties:
                  account_number:
                    type: string
                    name: account_number
                  account_type:
                    type: string
                    name: account_type
                  currency:
                    type: string
                    name: currency
            variable: message.body
            content: application/json
        actions:
        - set: output.account_number
          from: input.account_number
        - set: output.account_type
          from: input.account_type
        - set: output.currency
          from: input.currency
    - invoke:
        version: 2.2.0
        title: "lambda: get transactions"
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        http-version: HTTP/1.1
        timeout: 60
        verb: GET
        chunked-uploads: true
        persistent-connection: true
        cache-response: protocol
        cache-ttl: 900
        stop-on-error: []
        websocket-upgrade: false
        target-url: $(target-url)/accounts/{account_number}/transactions
        output: transactions
        graphql-send-type: detect
        description: Retrieves the transaction history for a specific account within the provided date range.
    - map:
        version: 2.0.0
        title: combine data for response
        inputs:
          transactions:
            schema:
              type: array
              items:
                type: object
                properties:
                  transaction_id:
                    type: string
                    name: transaction_id
                  date:
                    type: string
                    name: date
                  description:
                    type: string
                    name: description
                  amount:
                    type: number
                    name: amount
                  balance_after:
                    type: number
                    name: balance_after
            variable: transactions.body
          accounts:
            schema:
              type: array
              items:
                type: object
                properties:
                  account_number:
                    type: string
                    name: account_number
                  account_type:
                    type: string
                    name: account_type
                  currency:
                    type: string
                    name: currency
            variable: accounts.body
        outputs:
          output:
            schema:
              type: object
              properties:
                accounts:
                  type: array
                  items:
                    type: object
                    properties:
                      account_number:
                        type: string
                      transactions:
                        type: array
                        items:
                          type: object
                          properties:
                            transaction_id:
                              type: string
                            date:
                              type: string
                            description:
                              type: string
                            amount:
                              type: number
                            balance_after:
                              type: number
            variable: message.body
        actions:
        - set: output.accounts
          from: accounts
        - set: output.transactions
          from: transactions
    finally: []
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
x-original-swagger-version: "2.0"
