openapi: 3.0.1
info:
  title: balance-GlobalBank Account API
  description: Securely view account balances for GlobalBank customers.
  termsOfService: https://www.globalbank.com/terms
  contact:
    name: GlobalBank Support
    url: https://www.globalbank.com/support
  version: 1.0.0
  x-ibm-name: balance-globalbank-account-api
externalDocs:
  description: "GitHub project for this API, containing source code and deployment pipeline"
  url: https://github.com/globalbank/api-docs
servers:
  - url: /banking/v1
security:
  - clientID: []
paths:
  /accounts/{account_number}/balance:
    get:
      summary: Retrieve the current balance of a specific account.
      parameters:
        - name: account_number
          in: path
          description: The account number for which to retrieve the balance.
          required: true
          schema:
            type: string
            example: "1234567890"
      responses:
        "200":
          description: Account balance successfully retrieved
          content:
            application/json:
              schema:
                title: Account Balance
                type: object
                properties:
                  account_number:
                    title: Account Number
                    type: string
                    example: "1234567890"
                  balance:
                    title: Current Balance
                    type: number
                    format: float
                    example: 1200.50
                  currency:
                    title: Currency
                    type: string
                    example: "USD"
components:
  securitySchemes:
    clientID:
      type: apiKey
      name: X-IBM-Client-Id
      in: header
x-ibm-configuration:
  properties:
    target-url:
      value: "https://main--lighthearted-torrone-3976db.netlify.app/.netlify/functions/fetch-data"
      description: URL to retrieve account balance data from Netlify
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - invoke:
        version: 2.2.0
        title: "lambda: get balance"
        backend-type: detect
        header-control:
          type: blocklist
          values: []
        parameter-control:
          type: allowlist
          values: []
        http-version: HTTP/1.1
        timeout: 60
        verb: GET
        persistent-connection: true
        target-url: $(target-url)/accounts/{account_number}/balance
        output: balance
        description: Retrieves the balance for the specified account.
        
    - map:
        version: 2.0.0
        title: combine data for response
        inputs:
          accounts:
            schema:
              type: array
              items:
                type: object
                properties:
                  account_number:
                    type: string
                    name: account_number
                  balance:
                    type: number
                    name: balance
                  currency:
                    type: string
                    name: currency
            variable: accounts.body
        outputs:
          output:
            schema:
              type: object
              properties:
                accounts:
                  type: array
                  items:
                    type: object
                    properties:
                      account_number:
                        type: string
                      balance:
                        type: number
                      currency:
                        type: string
            variable: message.body
        actions:
        - set: output.accounts
          from: accounts
    finally: []
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
x-original-swagger-version: "2.0"
